----CREATE DATABASE EXPIRED_DOMAINS

--CREATE TABLE Godaddy_Auctions_STAGE
--(
--DOMAIN_NAME VARCHAR(90),
--ITEMID INT,
--AUCTION_TYPE VARCHAR(40),
--TIMELEFT VARCHAR(50),
--PRICE VARCHAR(10),
--BIDS INT,
--DOMAIN_AGE NUMERIC(8,2),
--TRAFFIC NUMERIC(8,2),
--VALUATIONPRICE VARCHAR(10)
--)

--CREATE TABLE Godaddy_Auctions_PROD
--(
--DOMAIN_NAME VARCHAR(90),
--ITEMID INT,
--AUCTION_TYPE VARCHAR(40),
--TIMELEFT DATETIME,
--PRICE MONEY,
--BIDS INT,
--DOMAIN_AGE NUMERIC(8,2),
--TRAFFIC NUMERIC(8,2),
--VALUATIONPRICE MONEY,
--PAGERANK INT DEFAULT -2,
--VALID_PR VARCHAR(7),
--MOZRANK DECIMAL(5,2),
--DOMAIN_AUTHORITY DECIMAL(5,2),
--PAGE_AUTHORITY DECIMAL(5,2),
--TOTAL_LINKS BIGINT,
--CRTE_TS DATE
--)
 
--CREATE PROC SP_STAGETOPROD AS
--BEGIN
--MERGE Godaddy_Auctions_PROD AS PROD
--USING Godaddy_Auctions_STAGE AS STAGE
--ON (PROD.ITEMID=STAGE.ITEMID) 
--WHEN NOT MATCHED BY TARGET AND STAGE.AUCTION_TYPE NOT LIKE 'Offer%' AND STAGE.DOMAIN_NAME NOT LIKE '%.info%' AND CAST(PRICE AS MONEY)<=300
--    THEN INSERT
--    (DOMAIN_NAME,
--    ITEMID,
--    AUCTION_TYPE,
--    TIMELEFT,
--    PRICE,
--    BIDS,
--    DOMAIN_AGE,
--    TRAFFIC,
--    VALUATIONPRICE,
--	CRTE_TS) 
--    VALUES
--    (STAGE.DOMAIN_NAME,
--    STAGE.ITEMID,
--    STAGE.AUCTION_TYPE,
--    CAST(SUBSTRING(STAGE.TIMELEFT,1,19) AS DATETIME),
--    STAGE.PRICE,
--    STAGE.BIDS,
--    STAGE.DOMAIN_AGE,
--    STAGE.TRAFFIC,
--    STAGE.VALUATIONPRICE,
--	  GETDATE())
--WHEN MATCHED AND PROD.AUCTION_TYPE LIKE '%BID%'
--    THEN UPDATE SET PROD.PRICE = STAGE.PRICE,PROD.BIDS=STAGE.BIDS
    
--WHEN NOT MATCHED BY SOURCE
--    THEN DELETE ;
--END


TRUNCATE TABLE Godaddy_Auctions_STAGE
TRUNCATE TABLE Godaddy_Auctions_PROD

BULK INSERT Godaddy_Auctions_STAGE
FROM 'C:\Users\Sandeep\Downloads\ts\tdnam_all_no_adult_listings3.csv'
WITH ( FIRSTROW = 2,FIELDTERMINATOR = ',',ROWTERMINATOR = '\n',TABLOCK)


INSERT INTO Godaddy_Auctions_PROD(DOMAIN_NAME,ITEMID,AUCTION_TYPE,TIMELEFT,PRICE,BIDS,DOMAIN_AGE,TRAFFIC,VALUATIONPRICE)
SELECT DOMAIN_NAME,ITEMID,AUCTION_TYPE,Substring(TIMELEFT, 1, (len(TIMELEFT) - 5) )TIMELEFT,PRICE,BIDS,DOMAIN_AGE,TRAFFIC,VALUATIONPRICE FROM Godaddy_Auctions_STAGE 
WHERE 
DOMAIN_NAME LIKE '%.COM%' 
AND AUCTION_TYPE LIKE 'BuyNow'



SELECT * FROM Godaddy_Auctions_PROD WHERE PRICE < 50 ORDER BY PRICE